
  CREATE TABLE "TJOEUNIT"."CATEGORY" 
   (	"IDX" NUMBER NOT NULL ENABLE, 
	"CATEGORY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"GUP" NUMBER, 
	"LEV" NUMBER, 
	"SEQ" NUMBER, 
	 CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
delete from category;
drop SEQUENCE category_idx_seq;
create SEQUENCE category_idx_seq;

insert into category (idx, category, gup, lev, seq) 
		values (category_idx_seq.nextval, ≥Î∆Æ∫œ, category_idx_seq.currval, 0, 0);
        
select * from category;

SELECT?*?FROM?all_tables?WHERE?table_name?=?'category'?;
select * from all_tables;